docs:
	./node_modules/.bin/jsdoc player.js server.js library.js voter.js args.js test/test-library.js test/test-player.js test/test-server.js test/test-voter.js public/home.js -d '../Doc/Generated Docs'
