docs: clean-docs
	./node_modules/.bin/jsdoc public/home.js server.js library.js voter.js metadata.js player.js error-handler.js args.js -d '../Doc/Generated Docs'
clean-docs:
	rm -rf '../Doc/Generated Docs'
